### ISSUE TITLE
incomplete name handling (empty string and space support)

### ISSUE THREAD

**Issue by csabahruska** [phaazon/wavefront#1]
It's quite common amongst OBJ files that they have empty group names or have spaces in names.
e.g.

```
# Max2Obj Version 4.0 Mar 10th, 2001
#
mtllib ./VAZ 2107.mtl
g 
# object wheel01 to come ...
#
v  824.404785 338.231079 1126.765625
v  842.479675 293.364044 1119.525024

o Rear Tires
v 1.5279 0.823908 -0.8357
```

It's not handled properly in wavefront-0.7.

**Comment by csabahruska** [comment]
is this solved?

**Comment by phaazon** [comment]
I don’t know, it’s been a while I haven’t been working on that. I should have a look at the PR you made months ago…
