### ISSUE TITLE
Bump base version in .cabal file

### ISSUE THREAD

**Issue by kitoran** [phaazon/wavefront#6]
The package builds perfectly fine with ghc-8.6.1 and base-4.12.0.0. Currently projects that depend on wavefront can't switch to hc-8.6.* because of base version restriction in wavefront.cabal. Please change the line 
  build-depends:       base         >= 4.8  && < 4.12
to 
  build-depends:       base         >= 4.8  && < 4.13

**Comment by phaazon** [comment]
Sure! Thanks for notifying!

**Comment by phaazon** [comment]
Fixed in 225f61fb1763f8b88fd33d8b0d81bfe096aefa3a.

**Comment by kitoran** [comment]
Thank you. In case you don't know this note that you don't need to release new package version to change metadata. How to do this and reasons for doing this are described here: https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md  Basically this reduces dependency hell a bit.
