### ISSUE TITLE
base dependency bump

### ISSUE THREAD

**Issue by cjay** [phaazon/wavefront#7]
Currently wants base < 4.13, but builds and seems to work fine with base 4.13 that comes with GHC 8.8. Tried with the Chalet model from the Vulkan tutorial, seems to render correctly.

**Comment by phaazon** [comment]
Thanks for pinging! I’ll make a change. :)

**Comment by phaazon** [comment]
[4.13 is not available](http://hackage.haskell.org/package/base), how did you get it?

**Comment by cjay** [comment]
I don't know why it's not on hackage, but it came with GHC. See the [GHC 8.8 migration guide](https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.8#base-41300). `ghc-pkg list` should mention it as globally installed.

**Comment by phaazon** [comment]
Published.

**Comment by cjay** [comment]
Same procedure for base 4.14 from GHC 8.10. Works with the Chalet demo. 4.15 is also out with GHC 9.0, but I could not test with that.

**Comment by phaazon** [comment]
With the Chalet demo? :)

**Comment by cjay** [comment]
The one from [here](https://github.com/cjay/vulkan/blob/master/vulkan-triangles/app/Main.hs) (linking my fork because of the 8.10 fix that isn't merged yet). It's a port of the end result of [vulkan-tutorial.com](https://vulkan-tutorial.com).

**Comment by cjay** [comment]
Alright, it works with viking_room.obj now. I'm not sure if the model lacks backward surfaces or if the culling settings are wrong, as I can see through the walls from behind when it rotates. I doubt it's a problem with this lib though.

**Comment by achirkin** [comment]
GHC 9.0 also seems to work.

**Comment by dpwiz** [comment]
> I'm not sure if the model lacks backward surfaces or if the culling settings are wrong, as I can see through the walls from behind when it rotates.

It's the same with glTF original from SketchFab.

**Comment by ScottFreeCode** [comment]
Looks like #8 fixes this.

**Comment by phaazon** [comment]
It does, but I was super late. I’ll make a new package available.

**Comment by phaazon** [comment]
[It’s here](https://hackage.haskell.org/package/wavefront-0.7.1.5).
